name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    - name: Zip dist folder
      run: zip -r dist.zip dist

    - name: Write SSH key to file
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Copy dist.zip to EC2 via SCP
      run: |
        scp -i key.pem -o StrictHostKeyChecking=no dist.zip ${{ secrets.EC2_HOST }}:~/dist.zip
  
    - name: Unzip on EC2
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << 'EOF'
          sudo rm -rf /var/www/html/*
          sudo unzip -o ~/dist.zip -d /var/www/html
        EOF
