name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    - name: Zip dist folder
      run: zip -r dist.zip dist

    - name: Copy dist.zip to EC2 via SCP
      run: |
        scp -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no dist.zip ${{ secrets.EC2_HOST }}:/home/ubuntu/

    - name: Unzip on EC2
      run: |
        ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << 'EOF'
          sudo rm -rf /var/www/html/*
          sudo unzip -o /home/ubuntu/dist.zip -d /var/www/html
        EOF
